### ISSUE TITLE
NullReferenceException when syncing with Google Calendar

### ISSUE THREAD

**Issue by wrstlbrnft** [aluxnimm/outlookcaldavsynchronizer#115]
I'm using v.1.18.0.0 on Outlook 2016. When syncing (two-way) with my Google calendar, I get a NullReferenceException, as shown in the attached screenshot.

![caldav-npe](https://cloud.githubusercontent.com/assets/3921172/13173476/fe6da5f0-d6fd-11e5-92c0-f38ca0133f26.jpg)

Is there a way to figure out what properties of the offending event cause the NRE so I can fix it by updating the event?

**Comment by aluxnimm** [comment]
Please provide the raw data of the offending server event. For that click on the link below "Server ID" to download the ics file. Attach it here that we can identify the problem.

**Comment by wrstlbrnft** [comment]
Here is the offending event. It was originally created on an Exchange calendar and I then copied it in Outlook to a local calendar which I sync with Google.
[offending.ics.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/137808/offending.ics.txt)

**Comment by aluxnimm** [comment]
Can't find anything offending in that ics file and can sync it from Google to Outlook without error. Since the sync is trying to update an existing Outlook item maybe in the Outlook appointment is some error. Delete the item in Outlook and change sync direction Outlook<-Server (Replicate) once to recreate it in Outlook to check if it can be created.

**Comment by wrstlbrnft** [comment]
I deleted the event and re-created it. Now it syncs fine.
I'm sorry if that prevented you from finding out more, which the replicate server->Outlook could have revealed.
Thank you very much for your help!
