### ISSUE TITLE
Missing text in README.txt

### ISSUE THREAD

**Issue by Riduidel** [aluxnimm/outlookcaldavsynchronizer#122]
Seems like there is something in the install part : 

    into the same folder and start setup.exe

Which folder are you talking about ? The Outlook one ?

**Comment by nertsch** [comment]
That means that all the files in the Zip file should be extracted into the same folder (since the zip file doesn't include a directoty structure this should happen by default). The folder can be any folder and you can delete it after the installation.
(I aggree that the text "into the same folder" is a little bit misleading)

br
Gerhard

**Comment by Riduidel** [comment]
OK, so, now I've extracted all that content "somewhere", where should I install Caldav synchronizer ? default path is built from application infos, which is OK. But it seems Outlook will only accept it as a plugin if it is installed in Outlook folder, no ?

**Comment by nertsch** [comment]
Outlook will only accept it, if it is installed on system drive (usually C:) . This limitation is due to security reasons. The folder doesn't matter. If you don't like the default folder you can pick another one.

br
Gerhard

**Comment by aluxnimm** [comment]
Updated README to clarify install directory.
