### ISSUE TITLE
Sync error with SOGo - System.AurgumentException.BYMONTHvalue 0 is out of range.

### ISSUE THREAD

**Issue by robertduren** [aluxnimm/outlookcaldavsynchronizer#147]
I have a SOGo email server and the client is outlook 2016.  I have other users using the caldav adapter without problem.  It looks like I am the only one having this error.  I receive an error with every sync, but it looks like everything is working.  My calendar and contacts both completely sync bidirectionally.  I am sure the problem is an error with my SOGo account.  When I look at my account settings in SOGo I do not see anything that sticks out at me. 

Any ideas where to start.  Please see the attached log files.

[30677a88-36ee-4df7-a5c7-a6d905d268c020160719141036000.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/374462/30677a88-36ee-4df7-a5c7-a6d905d268c020160719141036000.txt)
[f1a56185-9a58-4327-96e0-34e143dd00b420160720185544010.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/374461/f1a56185-9a58-4327-96e0-34e143dd00b420160720185544010.txt)

**Comment by ingoratsdorf** [comment]
You have a recurrance defined by BYMONTH with a month=0 which does not exist:

/SOGo/dav/robert.duren@theacesinc.com/Calendar/personal/20151101T194302726260.ics
System.ArgumentException: BYMONTH value 0 is out of range. Valid values are between 1 and 12, excluding zero (0).

/SOGo/dav/robert.duren@theacesinc.com/Calendar/personal/20151101T194319585237.ics
System.ArgumentException: BYMONTH value 0 is out of range. Valid values are between 1 and 12, excluding zero (0).

The last error is that an item cannot be found, which MAY go away when the other 2 errors ere resolved.

Since you are syncing TO Sogo, I would assume that the wrong calendar month specified is within the conversation in CalDAVSynchronizer.

**Comment by aluxnimm** [comment]
Those two events have incorrect recurrence rules as mentioned but the last sentence is wrong. This error doesn't come from the conversion in our client but when trying to import the events from SOGo, so they are wrong on the server (could have been from another client and SOGo accepted it). So delete or repair them on the server and sync again. The third one (/SOGo/dav/robert.duren@theacesinc.com/Calendar/personal/ae76c221-c573-4cb4-842a-b8bda0ad3ea3.ics) could also be some invalid data which causes a problem creating the corresponding outlook appointment. 

You can also post the raw ics data of those 3 events so that we can identify the exact errors.

**Comment by robertduren** [comment]
Thank you to both of you for your help.  That got me moving in the right direction.  I did find the problem is in my SOGo calendar.  I am working on deleting the corrupt data and I am confident that will fix it.  
Again, thank you.
