### ISSUE TITLE
Copied reoccurring calendar entry cannot be synced

### ISSUE THREAD

**Issue by maybeec** [aluxnimm/outlookcaldavsynchronizer#164]
I copied a reoccurring calendar entry from one calendar to another (copy, not move!). Both calendars are synced by outlookcaldavsynchronizer to owncloud 8.2.x. However, right after synchronization, the copied entry vanishes.

**Comment by aluxnimm** [comment]
is it a meeting with yourrself as organizer or an invite? can you post the log.txt part  of that sync?

**Comment by maybeec** [comment]
Basically, the whole scenario is the following:

I was creating this appointment once and invited my wife to share the appointment. Thus, I am the organizer.
Then due to any synchronization issue (I did not get recognized the point in time when it happened) my appointment series vanished.
Finally, I was trying to copy the appointment back from my wifes calendar to my calendar to just get the appointment series back. However, as written above, synchronization removes it again from my calendar.

Interestingly, I had a short look into the attendees list. It looks like the following: Me (organizer), my wife, me, me. So I am multiple times registered as an attendee. Might be a "feature" of Outlook :) of all this stuff going on while copying calendar entries. However, might that be an issue for synrhonization?

I will check, whether I also can provide a log at the weekend.

**Comment by aluxnimm** [comment]
Ok, don't need the log file anymore. Problem is similar to 
https://sourceforge.net/p/outlookcaldavsynchronizer/discussion/general/thread/ce763a1d/

It seems that copying the appointment makes Outlook set the MeetingStatus to MeetingReceived, but since you are the organizer and also an attendee our logic discards it to avoid doubled invitations. As a workaround you can remove the email adress in the sync profile, not needed in your case with Owncloud.

**Comment by maybeec** [comment]
worked out. thanks.
