### ISSUE TITLE
Add iCloud Calendars to Profile Wizard

### ISSUE THREAD

**Issue by fmms** [aluxnimm/outlookcaldavsynchronizer#212]
Hi,

I could not get the oficial Apple iCloud Software to work reliably in Outlook and thus  I tried this. It seems to wok perfectly, the sync is reliable and a lot faster.

However setting up the account is not very easy, because one has to determine the Apple server names und URL substrings. Most articles on the internet suggst to look at plist files in MacOS, however if one is not using that it becomes even less easy.

With a few HTTP request everything that is neccessary can be determined: https://stackoverflow.com/questions/42319487/icloud-calendar-requests . I think it would be great to have that integrated in the account wizard.

I am glad to test. Thanks for your work!

**Comment by aluxnimm** [comment]
Did you actually try with the DAV url https://caldav.icloud.com/ and use "Test or discover settings" ? We already implement the autodiscovery, so it should work and discover the calendar resources.

**Comment by fmms** [comment]
Hi,
you are right, this does indeed work. So this is not a missing functionality but more an issues of documentation I guess.

I read http://caldavsynchronizer.org/de/documentation/ with the heading "ICLOUD SETTNGS" it does not suggest that the short URL might be enough.
Looking at the profile wizard one assumes iCloud calendards are not done easily as iCloud contacts has its own icon.

thanks

**Comment by aluxnimm** [comment]
Yes, documentation needs an update because I couldn't test if it actually works also for calendar since I don't have an iOS device for testing atm and could only test the adressbook with the web UI. The problem is that the contacts and calendars needs different base urls caldav.icloud.com and contacts.icloud.com, that's why we only have the icon for the contacts atm but should add one for calendar as well since you confirmed the autodiscovery working.

**Comment by aluxnimm** [comment]
Finally had time to add this missing profile type in commit a4c5bdf and update docs.
