### ISSUE TITLE
Outlook CalDav Synchronizer: error synch recurring task with Open Xchange server

### ISSUE THREAD

**Issue by daphne777** [aluxnimm/outlookcaldavsynchronizer#292]
Hello,
following problem:
Caldav Synchronizer does not sync recurring task with Open-Xchange server.
Normal tasks (not recurring) are working fine.

Error report and LogFile in the attachment.

Data:
Windows10 (1909)
Outlook 2010 (also testet with 2016)
CalDavSynchronizer Version: 3.8.2.0
CalDav/Cardav Server und Version: UCS Server 4.4 / OX Version 7.10.4-ucs1
[ErrorReport.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/5428535/ErrorReport.txt)
[LogFile.txt](https://github.com/aluxnimm/outlookcaldavsynchronizer/files/5428537/LogFile.txt)

**Comment by aluxnimm** [comment]
Need to investigate if and how OX supports recurring tasks

**Comment by daphne777** [comment]
Hello Aluxnimm,

thanks for the fast reply.

I think OX supports recurring tasks.
On the web interface of Open-Xchange I can create recurring tasks,
but they are not synchronized with Outlook.

If you need more information just ask.

**Comment by aluxnimm** [comment]
Just tested this, it seems recurring tasks are not exposed via the CalDAV API. if I create such a task in OX it's not available in the collection, if I change the same task back to non recurring it gets synced. When trying to sync tasks with RRULE to the server, OX responds with 400 Bad Request. So I guess, they are not supported via CalDAV. I will ask the OX developers if this is by design.

**Comment by daphne777** [comment]
Hi Aluxnimm,
any answer from OX yet?

I hope it is a bug (not by design) and they will solve it with a update? :-)

**Comment by aluxnimm** [comment]
According to OX recurring tasks are not supported via CalDAV, since OX uses a different internal data model. So nothing we can do on our side atm.
I suggest turning off syncing of recurring tasks from Outlook in the advanced settings/task mapping configuration to avoid the error.

As a workaround you can create individual tasks or use recurring events in a seperate calendar collection used for tasks.
