### ISSUE TITLE
[BUG] Fails to authenticate with accentuated char in password

### ISSUE THREAD

**Issue by loxK** [aluxnimm/outlookcaldavsynchronizer#363]
When the user's password contains an accentuated character (verified with char `ù`), it fails to authenticate :

![image](https://user-images.githubusercontent.com/136687/176811667-0ed9d7cb-4101-4f39-9f32-230e027e02f6.png)

**Comment by loxK** [comment]
I think I found the issue: [caldavsynchronizer](https://github.com/aluxnimm/outlookcaldavsynchronizer) fails when there are some special characters in user's password.

It is a bug.

**Comment by aluxnimm** [comment]
What network settings to you use in the sync profile advanced settings? Is Force Basic Auth activated, does it make any difference if you turn it off or use preemtive auth?

**Comment by loxK** [comment]
It works with `Force Basic Auth` activated. 
`preemtive auth` doesn't change anything 

So, there is a workaround (thks), but password without accentuated chars do work with default settings whereas any password should work.

(sorry, forgot to specify that is connecting to Nextcloud 24 from Outlook 2206 on  Windows 10)

**Comment by aluxnimm** [comment]
When using force basic auth we manually write the authentication header and use base64 encoded data of the utf8 username and password fields, so that combination seems to work for special chars. Without that option we just use the default settings of the C# HttpClient and NetworkCredential classes, there is no way to change the Encoding there I guess, so I am not sure how to change the behaviour.

**Comment by loxK** [comment]
Are the C# libs closed source ?

**Comment by aluxnimm** [comment]
Will change force basic authentication where we manually add the header in the correct encoding as default for new profiles in the next release to fix those issues.
