### ISSUE TITLE
CardDAV sync specification

### ISSUE THREAD

**Issue by may-bee** [aluxnimm/outlookcaldavsynchronizer#92]
Which attributes are supported to be synced for CardDAV?
* Contact pictures?
* Notes?
* Multiple Mail adresses?
* Favorite phone number? (especially interesting for mobile phones, which is also be supported by owncloud for example)

Are there any known issues. I would guess so as CardDAV seems to be not the easiest protocol, especially as it is not implemented correctly by different server implementations :)
I have not tested synchronization for CardDAV so far.

**Comment by aluxnimm** [comment]
- Contact photos work for Outlook > 2007, in OL 2007 there are issues accessing the property
- Notes yes
- Outlook supports 3 email adresses, so we support them too
- you mean the PREF attribute? yes

We don't support Outlook distribution lists and only vcard 3.0 spec atm and you are right, since every server and client behaves differently there will be some minor issues, but we try to fix it of course.

**Comment by may-bee** [comment]
Thanks for the fast reply.
I will test the plugin with the latest owncloud server and I will give you some feedback soon.
